**Basic python**



In [ ]:
#factorial
def factorial(n):
  if (n==0 or n==1):
    return 1
  else:
    return(n * factorial(n-1))

print(factorial(5))

120


In [ ]:
#Simple Interest
def interest(a, t, r):
  return((a*t*r)/100)

print("The interest is: ",interest(300,7,1))

The interest is:  21.0


In [ ]:
#armstrong
def isArmstrong(n):
  sum = 0
  rem = n
  size = str(n)

  for i in len(size):
    rem = rem % 10
    sum += pow(rem,len(str(n)))

  return True if (sum == n) else False

print(isArmstrong(2))

In [ ]:
#area of circle
def area(r):
  pi = 3.14
  return pi*(r*r)

n = float(input("Enter radius of circle: "))
print(area(n))

Enter radius of circle: 2.3
16.610599999999998


In [ ]:
#sum of squares of 1st n numbers
def sumOfSquare(n):
  sum = 0
  for i in range(n+1):
    sum += i**2
  return sum

print(sumOfSquare(3))

14


In [ ]:
#ascii of char

def ascii(a):
  return ord(a)

a = input("Enter char: ")
print(ascii(a))

Enter char: X
88


In [ ]:
#prime number

def isPrime(n):

  flag = True

  for i in range(2, int(n/2)):
    if (n % i == 0):
      flag = False
      break
  if (flag == True):
    print(n, " is a prime number.")
  else:
    print(n, " is not a prime number.")

isPrime(6)

6  is not a prime number.


In [ ]:
#isFibonacci

def isfib(n):

**Arrays**

In [ ]:
#sum of array
def arraySum(a):
  sum = 0
  for i in range(len(a)):
    sum += a[i]
  return sum

arr = [1,2,3,4]
print("Sum of array is: ", arraySum(arr))

Sum of array is:  10


In [ ]:
#rotation of array

def rotateArray(arr, n, r):
  for i in range(r):
    temp = arr[0]
    for j in range(n-1):
      arr[j] = arr[j+1]
    arr[n-1] = temp
  return arr

arr = [1,2,3,4,5,6,7,8]
print(rotateArray(arr, len(arr), 2))

[3, 4, 5, 6, 7, 8, 1, 2]


In [ ]:
#remainder of array multiplication
def arrayMultiRem(arr, s):
  prod = 1
  for i in range(len(arr)):
    prod *= arr[i]
  return prod % s

arr = [100, 10, 5, 25, 35, 14]
print(arrayMultiRem(arr, 11))

9


List

In [ ]:
# swap first and last element of a list
def swapList(newList):
	newList[0], newList[-1] = newList[-1], newList[0]
	return newList

newList = [12, 35, 9, 56, 24]
print(swapList(newList))

[24, 35, 9, 56, 12]


In [ ]:
# check if an element exists in list
test_list = [1, 6, 3, 5, 3, 4]

for i in test_list:
	if(i == 4):
		print("Element Exists")

Element Exists


In [ ]:
# Reversing a list using two-pointer approach
def reverse_list(arr):
	left = 0
	right = len(arr)-1
	while (left < right):
		# Swap
		temp = arr[left]
		arr[left] = arr[right]
		arr[right] = temp
		left += 1
		right -= 1

	return arr

arr = [1, 2, 3, 4, 5, 6, 7]
print(reverse_list(arr))

In [ ]:
# program to multiply all values in the list using numpy.prod()

import numpy
list1 = [1, 2, 3]
list2 = [3, 2, 4]

result1 = numpy.prod(list1)
result2 = numpy.prod(list2)
print(result1)
print(result2)

6
24


In [ ]:
# Python program to find largest number in a list
list1 = [10, 20, 4, 45, 99]
list1.sort()
print("Largest element is:", list1[-1])

In [ ]:
# Python program to print Even Numbers in given range
start = int(input("Enter the start of range:"))
end = int(input("Enter the end of range:"))

for num in range(start, end + 1):

	if num % 2 != 0:
		print(num)

In [ ]:
# Python program to remove multiple elements from a list

list1 = [11, 5, 17, 18, 23, 50]

for elem in list1:
	if elem % 2 == 0:
		list1.remove(elem)

print("New list after removing all even numbers: ", list1)

In [ ]:
# Demonstrate Remove empty List

test_list = [5, 6, [], 3, [], [], 9]
print("The original list is : " + str(test_list))

while [] in test_list :
	test_list.remove([])

print("List after empty list removal : " + str(test_list))

The original list is : [5, 6, [], 3, [], [], 9]
List after empty list removal : [5, 6, 3, 9]


In [ ]:
# Break a list into chunks of size N in Python using itertool
my_list = [1, 2, 3, 4, 5,
		6, 7, 8, 9]
start = 0
end = len(my_list)
step = 3
for i in range(start, end, step):
	x = i
	print(my_list[x:x+step])

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [ ]:
# program to sort values of first list based on second list
list1 = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
list2 = [0, 1, 1, 0, 1, 2, 2, 0, 1]
a = list(set(list2))
a.sort()
res = []
for i in a:
	for j in range(0, len(list2)):
		if(list2[j] == i):
			res.append(list1[j])
print(res)

['a', 'd', 'h', 'b', 'c', 'e', 'i', 'f', 'g']


Matrix

In [ ]:
# addition and subtraction
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
#subtraction
print("Subtraction of two matrix")
print(np.subtract(A, B))
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [ ]:
import numpy as np

test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
print("The original list is : " + str(test_list))
K = 2
res = np.array(test_list)[:,K]
print("The Kth column of matrix is : " + str(res))

The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
The Kth column of matrix is : [ 6 10  5]


Dictionary

In [ ]:
#convert key values into flat dictionary
test_dict = {'month': [1, 2, 3], 'name': ['Jan', 'Feb', 'March']}
res = {test_dict['month'][i]: test_dict['name'][i] for i in range(len(test_dict['month']))}
print("Flattened dictionary:", res)

Flattened dictionary: {1: 'Jan', 2: 'Feb', 3: 'March'}


In [ ]:
#check order of char in string using ordererDict()

def check_order(string, pattern):
	i, j = 0, 0
	for char in string:
		if char == pattern[j]:
			j += 1
		if j == len(pattern):
			return True
		i += 1

	return False
string = 'engineers rock'
pattern = 'er'
print(check_order(string, pattern))

True


In [1]:
# Python code to demonstrate a dictionary with multiple inputs in a key.
import random as rn

dict = {}
x, y, z = 10, 20, 30
dict[x, y, z] = x + y - z;
x, y, z = 5, 2, 4
dict[x, y, z] = x + y - z;

print(dict)

{(10, 20, 30): 0, (5, 2, 4): 3}


In [2]:
# Remove all duplicates words from a given sentence
from collections import Counter

def remov_duplicates(input):

	input = input.split(" ")

	UniqW = Counter(input)

	s = " ".join(UniqW.keys())
	print (s)

if __name__ == "__main__":
	input = 'Python is great and Java is also great'
	remov_duplicates(input)

Python is great and Java also


In [ ]:
# function to mirror characters of a string

def mirrorChars(input,k):

	original = 'abcdefghijklmnopqrstuvwxyz'
	reverse = 'zyxwvutsrqponmlkjihgfedcba'
	dictChars = dict(zip(original,reverse))

	prefix = input[0:k-1]
	suffix = input[k-1:]
	mirror = ''

	for i in range(0,len(suffix)):
		mirror = mirror + dictChars[suffix[i]]

	print (prefix+mirror)

if __name__ == "__main__":
	input = 'paradox'
	k = 3
	mirrorChars(input,k)

In [4]:
# demonstrate working of Values Associated Keys Using setdefault()

test_dict = {'gfg' : [1, 2, 3], 'is' : [1, 4], 'best' : [4, 2]}

print("The original dictionary is : " + str(test_dict))

result_dict = {}
for key, val in test_dict.items():
	for ele in val:
		result_dict.setdefault(ele, []).append(key)

# printing result
print("The values associated dictionary : " + str(result_dict))

The original dictionary is : {'gfg': [1, 2, 3], 'is': [1, 4], 'best': [4, 2]}
The values associated dictionary : {1: ['gfg', 'is'], 2: ['gfg', 'best'], 3: ['gfg'], 4: ['is', 'best']}


Tuple


In [5]:
#Find the size of a Tuple in Python

import sys

# sample Tuples
Tuple1 = ("A", 1, "B", 2, "C", 3)
Tuple2 = ("Geek1", "Raju", "Geek2", "Nikhil", "Geek3", "Deepanshu")
Tuple3 = ((1, "Lion"), ( 2, "Tiger"), (3, "Fox"), (4, "Wolf"))

# print the sizes of sample Tuples
print("Size of Tuple1: " + str(sys.getsizeof(Tuple1)) + "bytes")
print("Size of Tuple2: " + str(sys.getsizeof(Tuple2)) + "bytes")
print("Size of Tuple3: " + str(sys.getsizeof(Tuple3)) + "bytes")

Size of Tuple1: 88bytes
Size of Tuple2: 88bytes
Size of Tuple3: 72bytes


In [6]:
# Closest Pair to Kth index element in Tuple

test_list = [(3, 4), (78, 76), (2, 3), (9, 8), (19, 23)]

tup = (17, 23)
K = 1

res = min(test_list, key=lambda x: abs(x[K-1] - tup[K-1]))

print("The nearest tuple to Kth index element is : " + str(res))

The nearest tuple to Kth index element is : (19, 23)
